### ISSUE TITLE
Output file??

### ISSUE THREAD

**Issue by CamsShaft** [mishakorzik/AdminHack#13]
Hey there! I'm just wondering if there's an output file or anything I can read to decipher what I can do with this after. Still pretty fresh and getting used to the commands and in shell environments. Thanks for any info. Have a great day!

**Comment by mishakorzik** [comment]
I add its later.

**Comment by M3hank** [comment]
> Hey there! I'm just wondering if there's an output file or anything I can read to decipher what I can do with this after. Still pretty fresh and getting used to the commands and in shell environments. Thanks for any info. Have a great day!

Fixed

**Comment by CamsShaft** [comment]
Thanks for that! Hope it wasn't too much trouble
