### ISSUE TITLE
Error : SyntaxError   File "src/serv.py", line 4

### ISSUE THREAD

**Issue by hmidani-abdelilah** [mishakorzik/AdminHack#4]
```
 File "src/serv.py", line 4
SyntaxError: Non-ASCII character '\xda' in file src/serv.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by mishakorzik** [comment]
This is the first time I've seen this error, but it means that your python doesn't support the compiler.

**Comment by mishakorzik** [comment]
try running python from different versions or reinstalling python.

**Comment by hmidani-abdelilah** [comment]
this error accured after i exculded the docker interface and others but its working properly on root privelege and sudo

**Comment by hmidani-abdelilah** [comment]
I used it in WSL, ubuntu 18.04 and it worked but i get this error and it would be better if the result was returned in a file

**Comment by mishakorzik** [comment]
sorry but AdminHack is not supported on ubuntu
