### ISSUE TITLE
Hey I problem have 3 lists of setup I needed 4 lists

### ISSUE THREAD

**Issue by Canasorngit** [mishakorzik/AdminHack#8]
Termux Linux and Kali Linux

Can you this terminal it called          
("Ish shell") it a Terminal like termux for iOS users it will help full

Thanks

**Comment by mishakorzik** [comment]
Can you please show a screenshot?

**Comment by Canasorngit** [comment]
> Can you please show a screenshot?

Here is it !

[image](https://user-images.githubusercontent.com/100019956/194875653-edf58b58-9ab7-4f16-a886-b4bd7121515f.jpeg)

It alpine linux shell called ish shell
