### ISSUE TITLE
No matching distribution found for smtp

### ISSUE THREAD

**Issue by kaifcodec** [mishakorzik/AdminHack#9]
When ever i excecute 'bash setup.sh' in my termux terminal It installs all the required packages but not smtp.
![Screenshot_20230308-075306](https://user-images.githubusercontent.com/98528577/223603243-bc3692fa-ed13-477c-bc1c-07e3c6461dac.png)
I am worried about smtp because it is not able to crack my router's admin password, where I use the correct password in the passlist it just ignores it and passes to next pass.
So, I think that it is happening because of the not installation of smtp.

**Comment by kaifcodec** [comment]
> Try update AdminHack

But how can I update? I reinstalled it but it wo'nt work.
Tell me the process to update 'AdminHack'.

**Comment by mishakorzik** [comment]
write this command: cd $HOME && rm -rf AdminHack

**Comment by mishakorzik** [comment]
And install AdminHack

**Comment by kaifcodec** [comment]
> 

I HAVE TRIED THAT MANY TIMES PREVIOUSLY BUT STILL IT OCCURS.
